### ISSUE TITLE
output disk size in check output / performance data

### ISSUE THREAD

**Issue by joke24** [usolved/check_usolved_disks#1] opened 2016-07-12 14:25 UTC
Hi,

it would be great to have the whole size of all disks in the performance-data output.
So that I can see the used space and the whole size of the disks in the graphs.

Would this be possible?

I'm gonna buy you a coke for that ;)

Thank's a lot

**Comment by usolved** [comment] 2016-07-20 14:21
I've looked into that issue and I don't think it's possible.
The problem is that the plugin returns multiple disks at once. The Nagios guideline sais, that multiple values can be seperated by a space in between.

**Guideline:**
`'label 1'=value[UOM];[warn];[crit];[min];[max] 'label 2'=value[UOM];[warn];[crit];[min];[max]`

**Example performance data:**
`Disk-C:=26.16GB;56;57;0;58.5 Disk-D:=1.32GB;74;76;0;78.1`

So every label will be put into one graph (or can be splitted in most of the tools).
If you wish to have the whole size of the disk _and_ the current state of the disk it would be like:

`Disk-C-All:=58.5GB;56;57;0;58.5 Disk-C-Current:=26.16GB;56;57;0;58.5 Disk-D-All:=78.1GB;74;76;0;78.1 Disk-D-Current:=1.32GB;74;76;0;78.1`

But I don't think it is a good way to solve this issue.
It's easier when you have a plugin like memory check. So you just have "size" and "used" space seperated and therefore you have both information in a single graph.

Actually the maximum value is already in the performace data (last attribute in the example above "58.5"), but most tools (that translates performance data into a graph) don't use this value. If you use centreon or pnp there's maybe a setting to also show the graph for the min and max value.

So I like to close this issue, since I can't quite solve it with an update.

**Closed as completed by usolved** 2016-07-20 14:21 UTC
Labels: enhancement
